ASPNETTRY/Models/Category.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ASPNETTRY.Models
{
    public class Category
    {
        public int CategoryID { get; set; }
        public string Name { get; set; }
    }
}

ASPNETTRY/Models/ErrorViewModel.cs
using System;

namespace ASPNETTRY.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ASPNETTRY/Models/Product.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ASPNETTRY.Models
{
    public class Product
    {
        public Product()
        {

        }
        public int ProductID { get; set; }
        public string Name { get; set; }
        public double Price { get; set; }
        public int CategoryID { get; set; }
        public int OnSale { get; set; }
        public int StockLevel { get; set; }
        public IEnumerable<Category> Categories { get; set; }

    }
}

ASPNETTRY/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using ASPNETTRY.Models;

namespace ASPNETTRY.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ASPNETTRY/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ASPNETTRY.Models;
using Microsoft.AspNetCore.Mvc;

namespace ASPNETTRY.Controllers
{
    public class ProductController : Controller
    {

        private readonly IProductRepository repo;

        public ProductController(IProductRepository repo)
        {
            this.repo = repo;
        }

        //GET: /<controller>/
        public IActionResult Index()
        {
            var products = repo.GetAllProducts();
            return View(products);
        }
        public IActionResult ViewProduct(int id)
        {
            var product = repo.GetProduct(id);

            return View(product);
        }
        public IActionResult UpdateProduct(int id)
        {
            Product prod = repo.GetProduct(id);

            repo.UpdateProduct(prod);

            if (prod == null)
            {
                return View("ProductNotFound");
            }

            return View(prod);
        }
        public IActionResult UpdateProductToDatabase(Product product)
        {
            repo.UpdateProduct(product);

            return RedirectToAction("ViewProduct", new { id = product.ProductID });
        }
        public IActionResult InsertProduct()
        {
            var prod = repo.AssignCategory();

            return View(prod);
        }
        public IActionResult InsertProductToDatabase(Product productToInsert)
        {
            repo.InsertProduct(productToInsert);

            return RedirectToAction("Index");
        }
        public IActionResult DeleteProduct(Product product)
        {
            repo.DeleteProduct(product);

            return RedirectToAction("Index");
        }





    }
}

ASPNETTRY/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

ASPNETTRY/Views/Product/Index.cshtml
@model IEnumerable<Product>

<h2>Products</h2>

<div style="display: block">
    <a href="/Product/InsertProduct/">Create a New Product</a>
</div>


<table class=“table”>
    <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Price</th>
        <th>Category ID</th>
        <th>On Sale</th>
        <th>Stock Level</th>
    </tr>
    @foreach (var product in Model)
    {
        <tr>
            <td><a href=/Product/ViewProduct/@product.ProductID>@product.ProductID</a></td>
            <td>@product.Name</td>
            <td>@product.Price</td>
            <td>@product.CategoryID</td>
            <td>@product.OnSale</td>
            <td>@product.StockLevel</td>

        </tr>
    }
</table>

ASPNETTRY/Views/Product/InsertProduct.cshtml
@model Product
<h2>Create a New Product</h2>
@using (Html.BeginForm("InsertProductToDatabase", "Product", "Post"))
{
    <input asp-for="ProductID" type="hidden" value="" />
    <label asp-for="Name" class="control-label">Name</label>
    <input type="text" name="Name" class="form-control" value="" />
    <label asp-for="Price" class="control-label">Price</label>
    <input type="number" step="0.01" name="Price" class="form-control" />
    <div class="form-group">
        <label for="">Select a Category</label>
        <select class="form-control" name="CategoryID" value="">
            @foreach (var cat in Model.Categories)
            {
                <option value="@cat.CategoryID">@cat.CategoryID @cat.Name</option>
            }
        </select>
    </div>
    <input type="submit" value="Create Product" class="btn btn-primary" />
}

ASPNETTRY/Views/Product/UpdateProductView.cshtml
@model Product

<h2>Update @Model.Name</h2>

@using (Html.BeginForm("UpdateProductToDatabase", "Product", "Post"))
{
    <input asp-for="ProductID" type="hidden" value="@Model.ProductID" />

    <label asp-for="Name" class="control-label">Name</label>

    <input type="text" name="Name" class="form-control" value="@Model.Name" />

    <label asp-for="Price" class="control-label">Price</label>

    <input type="number" step="0.01" name="Price" class="form-control" value="@Model.Price" />

    <input type="submit" value="Update Product" class="btn btn-primary" />

}

ASPNETTRY/Views/Product/ViewProduct.cshtml
@model Product

<h3>@Model.Name Information</h3>

<table class="table">
    <tr>
        <th>Product ID</th>
        <th>Name</th>
        <th>Price</th>
        <th>Category ID</th>
        <th>On Sale</th>
        <th>StockLevel</th>
    </tr>
    <tr>
        <td>@Model.ProductID</td>
        <td>@Model.Name</td>
        <td>@Model.Price</td>
        <td>@Model.CategoryID</td>
        <td>@Model.OnSale</td>
        <td>@Model.StockLevel</td>
    </tr>

</table>

<div style="display: block">
    <a href="/Product/UpdateProduct/@Model.ProductID">Update this Product</a>
</div>

<div style="display: block">
    @using (Html.BeginForm("DeleteProduct", "Product", "Post"))
    {
        <input type="hidden" asp-for="ProductID" value="@Model.ProductID" />
        <input type="submit" onclick="return confirm('Are you sure?')" value="Delete this product" />
    }
</div>

ASPNETTRY/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ASPNETTRY</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ASPNETTRY</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="Index">Products</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - ASPNETTRY - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>